cognitiveSearch:
  key: '{{searchAdminKey}}'
  endpoint: '{{searchEndpoint}}'
  indexName: 'vector-index'
  maxVectorSearchResults: 10
openAi:
  completionsDeployment: 'completions'
  completionsDeploymentMaxTokens: 8096
  embeddingsDeployment: 'embeddings'
  embeddingsDeploymentMaxTokens: 8191
  chatCompletionPromptName: 'RetailAssistant.Default'
  shortSummaryPromptName: 'Summarizer.TwoWords'
  promptOptimization:
    completionsMinTokens: 50
    completionsMaxTokens: 300
    systemMaxTokens: 1500
    memoryMinTokens: 1500
    memoryMaxTokens: 7000
    messagesMinTokens: 100
    messagesMaxTokens: 200
  endpoint: '{{openAiEndpoint}}'
  key: '{{openAiKey}}'
cosmosDb:
  containers: 'completions, customer, product'
  monitoredContainers: 'customer, product'
  database: 'database'
  changeFeedLeaseContainer: 'leases'
  endpoint: '{{cosmosEndpoint}}'
  key: '{{cosmosKey}}'
durableSystemPrompt:
  blobStorageContainer: 'system-prompt'
  blobStorageConnection: '{{blobStorageConnectionString}}'
cognitiveSearchMemorySource:
  configBlobStorageContainer: 'memory-source'
  configFilePath: 'ACSMemorySourceConfig.json'
  configBlobStorageConnection: '{{blobStorageConnectionString}}'
  key: '{{searchAdminKey}}'
  endpoint: '{{searchEndpoint}}'
blobStorageMemorySource:
  configBlobStorageContainer: 'memory-source'
  configFilePath: 'BlobMemorySourceConfig.json'
  configBlobStorageConnection: '{{blobStorageConnectionString}}'
chat:
  defaultOrchestrationService: 'SemanticKernel'
langChain:
  apiUrl: 'https://solliance-data-copilot-langchain-api.azurewebsites.net'
  apiKey: '{{langChainApiKey}}'
apiUrl: {{apiUrl}}
routePrefix: /core
applicationInsights:
  connectionString: "{{aiConnectionString}}"
langchainapi:
  keyVaultUrl: '{{keyVaultUrl}}'
  miClientId: '{{langChainApiMiClientId}}'
appConfig:
  uri: {{appConfigEndpoint}}
  connectionString: {{appConfigConnectionString}}
azureWorkloadIdentity:
  agentFactoryApiClientId: {{langChainApiMiClientId}}
  agentHubApiClientId: {{langChainApiMiClientId}}
  chatUiClientId: {{langChainApiMiClientId}}
  coreApiClientId: {{langChainApiMiClientId}}
  dataSourceHubApiClientId: {{langChainApiMiClientId}}
  gatekeeperApiClientId: {{langChainApiMiClientId}}
  langChainApiClientId: {{langChainApiMiClientId}}
  promptHubApiClientId: {{langChainApiMiClientId}}
  semanticKernelApiClientId: {{langChainApiMiClientId}}
  tenantId: {{tenantId}}