name: Core API Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: core-api
      context: ./src
      dockerfile: ./src/dotnet/CoreAPI/Dockerfile
